create table users
(
    id        bigint generated by default as identity
        primary key,
    blocked   boolean not null,
    password  varchar(255),
    user_role varchar(255)
        constraint users_user_role_check
            check ((user_role)::text = 'USER'::text),
    username  varchar(255)
);

alter table users
    owner to postgres;

create table jwt_refresh_token
(
    id         bigint generated by default as identity
        primary key,
    token      varchar(2048)
        constraint ukie2a78nhskfds91poygrspas7
            unique,
    token_type varchar(255)
        constraint jwt_refresh_token_token_type_check
            check ((token_type)::text = ANY
                   ((ARRAY ['ACCESS'::character varying, 'REFRESH'::character varying])::text[])),
    user_id    bigint
        constraint ukcbk6pwcbba3q5mj3ianb0uka0
            unique
        constraint fkho203er8vx2wu6or8fbj2obcs
            references users
);

alter table jwt_refresh_token
    owner to postgres;