version: '3'
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: books_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "%Nw8Fm1qc*HXFh3mK}|9GOzATC}8LQrh"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s
    networks:
      - app-network

  backend:
    build:
      context: ./book_service 
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/books_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "%Nw8Fm1qc*HXFh3mK}|9GOzATC}8LQrh"
    networks:
      - app-network
      - default

volumes:
  db-data:

networks:
  app-network: