create table book_entity
(
    id          bigint generated by default as identity
        primary key,
    author      varchar(255) not null,
    description varchar(255),
    genre       varchar(255),
    isbn        varchar(255) not null
        constraint uk552w50li26dx123ol1y39ja1w
            unique,
    title       varchar(255) not null
);

alter table book_entity
    owner to postgres;